apiVersion: v1
kind: Service
metadata:
  name: node-cellar-svc
  labels:
    name: node-cellar
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: node-cellar
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: node-cellar
  name: noce-cellar-controller
spec:
  replicas: 2
  selector:
    name: node-cellar
  template:
    metadata:
      labels:
        name: node-cellar
    spec:
      containers:
      - image: sonvn/nodecellar
        name: node-cellar
        env: MONGO_HOST=mongo
        ports:
        - containerPort: 3000
    
